SELECT P.PRODUCT_ID, PRODUCT_NAME , SUM(PRICE * AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT AS P
RIGHT JOIN FOOD_ORDER AS O
ON O.PRODUCT_ID = P.PRODUCT_ID
WHERE YEAR(PRODUCE_DATE) = 2022
AND MONTH(PRODUCE_DATE) = 5
AND NOT P.PRODUCT_ID IS NULL
GROUP BY P.PRODUCT_ID
ORDER BY SUM(PRICE * AMOUNT) DESC,
P.PRODUCT_ID ASC