SELECT YEAR(A.SALES_DATE), MONTH(A.SALES_DATE), 
    COUNT(DISTINCT A.USER_ID) AS PUCHASED_USERS, 
    ROUND(COUNT(DISTINCT A.USER_ID) / C.users, 1) AS PUCHASED_RATIO 
FROM (
    ONLINE_SALE A, (
        SELECT COUNT(*) AS USERS 
        FROM USER_INFO B 
        WHERE YEAR(B.JOINED) = 2021
    ) C
)
LEFT JOIN USER_INFO D ON A.USER_ID = D.USER_ID
WHERE YEAR(D.JOINED) = 2021
GROUP BY YEAR(A.SALES_DATE), MONTH(A.SALES_DATE)
ORDER BY YEAR(A.SALES_DATE), MONTH(A.SALES_DATE)