SELECT PRODUCT_CODE, (PRICE * SUM) AS SALES
FROM PRODUCT AS P
JOIN (
    SELECT PRODUCT_ID, SUM(SALES_AMOUNT) AS SUM
    FROM OFFLINE_SALE
    GROUP BY PRODUCT_ID
) S
ON P.PRODUCT_ID = S.PRODUCT_ID
ORDER BY (PRICE * SUM) DESC, PRODUCT_CODE ASC