SELECT P.CATEGORY, MPRICE AS MAX_PRICE, F.PRODUCT_NAME
FROM (
    SELECT MAX(PRICE) AS MPRICE, CATEGORY
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
    GROUP BY CATEGORY
) P
,FOOD_PRODUCT AS F
WHERE P.MPRICE = F.PRICE
AND P.CATEGORY = F.CATEGORY
ORDER BY MPRICE DESC