SELECT M.APNT_NO, M.PT_NAME, M.PT_NO, M.MCDP_CD, D.DR_NAME, M.APNT_YMD
FROM (
    SELECT A.APNT_NO, P.PT_NAME, A.PT_NO, A.MCDP_CD, A.APNT_YMD, A.MDDR_ID
    FROM PATIENT AS P
    JOIN (
        SELECT *
        FROM APPOINTMENT
        WHERE 
        YEAR(APNT_YMD) = 2022
        AND MONTH(APNT_YMD) = 4
        AND DAY(APNT_YMD) = 13
        AND APNT_CNCL_YN = 'N'
    ) AS A
    ON P.PT_NO = A.PT_NO
) AS M
JOIN DOCTOR AS D
ON M.MDDR_ID = D.DR_ID
ORDER BY APNT_YMD ASC, PT_NO ASC